version: '2'
services:
  phar:
    image: ctftraining/suctf_2019_upload_labs_2
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:9025:80"
    environment:
      - FLAG=flag{test_flag}
